-- Precomputed stats cache (regenerated by the seeder). value = JSON.
-- Keys: home:<scope>  (home-page payload)  ·  explore:<scope>  (default first page)
-- where <scope> is 'global' or a biobank slug.
CREATE TABLE IF NOT EXISTS stats (
	key TEXT PRIMARY KEY,
	value TEXT NOT NULL
);
