import { sql } from 'drizzle-orm';
import { integer, real, sqliteTable, text, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const biobanks = sqliteTable(
	'biobanks',
	{
		id: integer('id').primaryKey(),
		slug: text('slug').notNull(),
		name: text('name').notNull(),
		description: text('description').notNull().default(''),
		website: text('website').notNull().default('')
	},
	(t) => [index('biobanks_slug_idx').on(t.slug)]
);

export const populations = sqliteTable(
	'populations',
	{
		id: integer('id').primaryKey(),
		biobankId: integer('biobank_id').notNull(),
		name: text('name').notNull(),
		country: text('country').notNull(),
		countryCode: text('country_code').notNull(),
		adminLevel: text('admin_level').notNull().default('country'),
		lat: real('lat').notNull(),
		lon: real('lon').notNull()
	},
	(t) => [index('populations_biobank_name_idx').on(t.biobankId, t.name), index('populations_country_code_idx').on(t.countryCode)]
);

export const populationCountryMappings = sqliteTable(
	'population_country_mappings',
	{
		id: integer('id').primaryKey(),
		populationId: integer('population_id').notNull(),
		country: text('country').notNull(),
		countryCode: text('country_code').notNull(),
		regionGroup: text('region_group').notNull().default(''),
		subpopulationCode: text('subpopulation_code').notNull().default(''),
		subpopulationName: text('subpopulation_name').notNull().default(''),
		sampleCount: integer('sample_count').notNull().default(0)
	},
	(t) => [
		index('population_country_mappings_population_idx').on(t.populationId),
		index('population_country_mappings_country_idx').on(t.countryCode)
	]
);

export const cohorts = sqliteTable(
	'cohorts',
	{
		id: integer('id').primaryKey(),
		biobankId: integer('biobank_id').notNull(),
		populationId: integer('population_id').notNull(),
		datasetId: integer('dataset_id'),
		label: text('label').notNull(),
		assay: text('assay').notNull().default('unknown'),
		release: text('release').notNull().default(''),
		sampleCount: integer('sample_count').notNull().default(0)
	},
	(t) => [
		index('cohorts_biobank_population_idx').on(t.biobankId, t.populationId),
		index('cohorts_population_idx').on(t.populationId),
		index('cohorts_dataset_idx').on(t.datasetId)
	]
);

// A dataset = a tenant-owned collection of cohorts, with free-form JSON metadata
// (title, description, assay, build, capability flags like showGenotypeCounts, …).
// Its variants are those with a frequency in any of its cohorts.
export const datasets = sqliteTable(
	'datasets',
	{
		id: integer('id').primaryKey(),
		biobankId: integer('biobank_id').notNull(),
		slug: text('slug').notNull(),
		metadata: text('metadata').notNull().default('{}')
	},
	(t) => [index('datasets_biobank_id_idx').on(t.biobankId, t.id), index('datasets_slug_idx').on(t.slug)]
);

// Precomputed JSON stats cache (home payload + default explore page per scope),
// regenerated by the seeder so hot pages don't run live aggregations.
export const stats = sqliteTable('stats', {
	key: text('key').primaryKey(),
	value: text('value').notNull()
});

export const variants = sqliteTable(
	'variants',
	{
		id: integer('id').primaryKey(),
		chrom: integer('chrom').notNull(),
		pos: integer('pos').notNull(),
		ref: text('ref').notNull(),
		alt: text('alt').notNull(),
		rsid: integer('rsid'),
		vrsDigest: text('vrs_digest'),
		posHg19: integer('pos_hg19'),
		lifted: integer('lifted').notNull().default(0),
		vepLabel: text('vep_label'),
		vepImpact: text('vep_impact'),
		hgvsConsequence: text('hgvs_consequence'),
		vepHasMultipleConsequences: integer('vep_has_multiple_consequences').notNull().default(0)
	},
	(t) => [
		uniqueIndex('variants_locus_idx').on(t.chrom, t.pos, t.ref, t.alt),
		index('variants_rsid_idx').on(t.rsid),
		index('variants_chrom_pos_idx').on(t.chrom, t.pos),
		index('variants_chrom_pos_id_idx').on(t.chrom, t.pos, t.id),
		index('variants_vrs_digest_idx').on(t.vrsDigest),
		index('variants_vep_impact_locus_idx').on(t.vepImpact, t.chrom, t.pos, t.id),
		index('variants_vep_label_locus_idx').on(t.vepLabel, t.chrom, t.pos, t.id),
		index('variants_hgvs_consequence_idx').on(t.hgvsConsequence)
	]
);

export const genes = sqliteTable(
	'genes',
	{
		id: integer('id').primaryKey(),
		ensemblId: text('ensembl_id').notNull(),
		symbol: text('symbol').notNull(),
		symbolNorm: text('symbol_norm').notNull(),
		chrom: integer('chrom').notNull(),
		start: integer('start').notNull(),
		end: integer('end').notNull(),
		strand: text('strand').notNull(),
		geneType: text('gene_type').notNull()
	},
	(t) => [
		index('genes_symbol_norm_idx').on(t.symbolNorm),
		index('genes_region_idx').on(t.chrom, t.start, t.end),
		index('genes_symbol_norm_region_idx').on(t.symbolNorm, t.chrom, t.start, t.end),
		index('genes_chrom_start_end_symbol_idx').on(t.chrom, t.start, t.end, t.symbolNorm)
	]
);

export const frequencies = sqliteTable(
	'frequencies',
	{
		variantId: integer('variant_id').notNull(),
		cohortId: integer('cohort_id').notNull(),
		biobankId: integer('biobank_id').notNull(),
		ac: integer('ac').notNull(),
		an: integer('an').notNull(),
		af: real('af').notNull(),
		nHomo: integer('n_homo'),
		nHetero: integer('n_hetero'),
		nHomoRef: integer('n_homo_ref'),
		acMasked: integer('ac_masked').notNull().default(0),
		publicAc: integer('public_ac'),
		publicAf: real('public_af'),
		acUpperBound: integer('ac_upper_bound'),
		afUpperBound: real('af_upper_bound'),
		genotypeMasked: integer('genotype_masked').notNull().default(0),
		publicNHetero: integer('public_n_hetero'),
		publicNHomo: integer('public_n_homo'),
		publicNHomoRef: integer('public_n_homo_ref')
	},
	(t) => [
		primaryKey({ columns: [t.variantId, t.cohortId] }),
		index('frequencies_cohort_idx').on(t.cohortId),
		index('frequencies_biobank_idx').on(t.biobankId),
		index('frequencies_cohort_variant_idx').on(t.cohortId, t.variantId),
		index('frequencies_variant_public_af_idx').on(t.variantId, t.publicAf),
		index('frequencies_biobank_variant_public_af_idx').on(t.biobankId, t.variantId, t.publicAf),
		index('frequencies_variant_observed_idx').on(t.variantId).where(sql`ac > 0`),
		index('frequencies_biobank_variant_observed_idx').on(t.biobankId, t.variantId).where(sql`ac > 0`),
		index('frequencies_cohort_variant_observed_idx').on(t.cohortId, t.variantId).where(sql`ac > 0`),
		index('frequencies_public_af_variant_observed_idx').on(t.publicAf, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`),
		index('frequencies_public_ac_variant_observed_idx').on(t.publicAc, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`),
		index('frequencies_biobank_public_af_variant_observed_idx').on(t.biobankId, t.publicAf, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`),
		index('frequencies_biobank_public_ac_variant_observed_idx').on(t.biobankId, t.publicAc, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`),
		index('frequencies_cohort_public_af_variant_observed_idx').on(t.cohortId, t.publicAf, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`),
		index('frequencies_cohort_public_ac_variant_observed_idx').on(t.cohortId, t.publicAc, t.variantId).where(sql`ac > 0 AND public_ac IS NOT NULL`)
	]
);
