import { integer, real, sqliteTable, text, primaryKey, index, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const biobanks = sqliteTable('biobanks', {
	id: integer('id').primaryKey(),
	slug: text('slug').notNull(),
	name: text('name').notNull(),
	description: text('description').notNull().default(''),
	website: text('website').notNull().default('')
});

export const populations = sqliteTable('populations', {
	id: integer('id').primaryKey(),
	biobankId: integer('biobank_id').notNull(),
	name: text('name').notNull(),
	country: text('country').notNull(),
	countryCode: text('country_code').notNull(),
	adminLevel: text('admin_level').notNull().default('country'),
	lat: real('lat').notNull(),
	lon: real('lon').notNull()
});

export const cohorts = sqliteTable('cohorts', {
	id: integer('id').primaryKey(),
	biobankId: integer('biobank_id').notNull(),
	populationId: integer('population_id').notNull(),
	datasetId: integer('dataset_id'),
	label: text('label').notNull(),
	assay: text('assay').notNull().default('unknown'),
	release: text('release').notNull().default(''),
	sampleCount: integer('sample_count').notNull().default(0)
});

// A dataset = a tenant-owned collection of cohorts, with free-form JSON metadata
// (title, description, assay, build, capability flags like showGenotypeCounts, …).
// Its variants are those with a frequency in any of its cohorts.
export const datasets = sqliteTable('datasets', {
	id: integer('id').primaryKey(),
	biobankId: integer('biobank_id').notNull(),
	slug: text('slug').notNull(),
	metadata: text('metadata').notNull().default('{}')
});

// Precomputed JSON stats cache (home payload + default explore page per scope),
// regenerated by the seeder so hot pages don't run live aggregations.
export const stats = sqliteTable('stats', {
	key: text('key').primaryKey(),
	value: text('value').notNull()
});

export const variants = sqliteTable(
	'variants',
	{
		id: integer('id').primaryKey(),
		chrom: integer('chrom').notNull(),
		pos: integer('pos').notNull(),
		ref: text('ref').notNull(),
		alt: text('alt').notNull(),
		rsid: integer('rsid'),
		vrsDigest: text('vrs_digest'),
		posHg19: integer('pos_hg19'),
		lifted: integer('lifted').notNull().default(0)
	},
	(t) => [
		uniqueIndex('variants_locus_idx').on(t.chrom, t.pos, t.ref, t.alt),
		index('variants_rsid_idx').on(t.rsid),
		index('variants_chrom_pos_idx').on(t.chrom, t.pos)
	]
);

export const genes = sqliteTable(
	'genes',
	{
		id: integer('id').primaryKey(),
		ensemblId: text('ensembl_id').notNull(),
		symbol: text('symbol').notNull(),
		symbolNorm: text('symbol_norm').notNull(),
		chrom: integer('chrom').notNull(),
		start: integer('start').notNull(),
		end: integer('end').notNull(),
		strand: text('strand').notNull(),
		geneType: text('gene_type').notNull()
	},
	(t) => [index('genes_symbol_norm_idx').on(t.symbolNorm), index('genes_region_idx').on(t.chrom, t.start, t.end)]
);

export const frequencies = sqliteTable(
	'frequencies',
	{
		variantId: integer('variant_id').notNull(),
		cohortId: integer('cohort_id').notNull(),
		biobankId: integer('biobank_id').notNull(),
		ac: integer('ac').notNull(),
		an: integer('an').notNull(),
		af: real('af').notNull(),
		nHomo: integer('n_homo'),
		nHetero: integer('n_hetero'),
		nHomoRef: integer('n_homo_ref')
	},
	(t) => [
		primaryKey({ columns: [t.variantId, t.cohortId] }),
		index('frequencies_cohort_idx').on(t.cohortId),
		index('frequencies_biobank_idx').on(t.biobankId)
	]
);
